### ISSUE TITLE
bot stopped working from 15 July evening

### ISSUE THREAD

**Issue by ashishnetworks** [folz/cleverbot.py#16]
Its not responding to any question. It used to work a few hours from now but suddenly it stopped working. And the code is exactly same. Even the example code provided with this API is not working :(
probably their API might have been changed

**Comment by ashishnetworks** [comment]
suddenly started working again ..

**Comment by ionuthulub** [comment]
Let us know if the issue appears again.

**Comment by CrazyPython** [comment]
If it detects something (e.g. configuring two bots to talk to each other) it will say "I am not sure you are a human" or something like that and start sending ads prefixed with a newline. Configure your script to sleep with `random.random()` instead of a static number and it will think you are a human.

**Comment by ionuthulub** [comment]
Just tested the examples and they work so I'll close this for now. Let me know if you run into this issue again.
