### ISSUE TITLE
Index error - again

### ISSUE THREAD

**Issue by ConorT38** [folz/cleverbot.py#44]
Currently running on the 1.1.1 version, and I am still getting the
if parsed[0][1] == 'DENIED' error.

simply put in cb.ask("hi")

any solutions?

**Comment by vikingiwan** [comment]
Yep, I'm also getting this error. I've been using cleverbot.py for about 2 weeks now and haven't had any problems until today where it suddenly just began giving me this error.

**Comment by TomG777** [comment]
The code on the side of cleverbot got changed again. Because of this the url the library connects to needs to be changed, the pull request by aurieh fixes this.

The fix can be done by changing the `RESOURCE = "/webservicemin?uc=321&"` line to `RESOURCE = "/webservicemin?uc=3210&botapi=[YOUR_API_NAME]"` where you put a new name instead of [YOUR_API_NAME]. 
(It is probably best to choose a unique name as this gives the best chance to not get shut off from using the API).
In my case the script file could be found at `\lib\site-packages\cleverbot\cleverbot.py` prefixed by your python install location, yours will probably be the same.

**Comment by vikingiwan** [comment]
Thanks! that fixed it right up

**Comment by Atomicbeast101** [comment]
Worked for me!

**Comment by folz** [comment]
Hey all - if you update to v2.0.0 you'll be able to customize your botapi name without having to maintain a fork.
